version: "3"
services:
  mysql:
    container_name: mysql-container
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - CHARACTER-SET-SERVER=utf8mb4 
